westcoast-education.web/Controllers/PersonsAdminController.cs
using Microsoft.AspNetCore.Mvc;
using westcoast_education.web.Interfaces;
using westcoast_education.web.Models;
using westcoast_education.web.ViewModels.Persons;


namespace westcoast_education.web.Controllers
{
    [Route("personsadmin")]
    public class PersonsAdminController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public PersonsAdminController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            
        }

        public async Task<IActionResult> Index()
        {
            var result = await _unitOfWork.PersonRepository.ListAllAsync();
            var persons = result.Select(p => new PersonsListViewModel
            {
                PersonId = p.PersonId,
                PersonUserName = p.PersonUserName,
                PersonTitle = p.PersonTitle,
                PersonName = p.PersonName,
                PersonLastName = p.PersonLastName,
                PersonEmail = p.PersonEmail,
                PersonPhone = p.PersonPhone

            }).ToList();


            return View("Index", persons);

        }

        [HttpGet("create")]
        public IActionResult Create()
        {
            var person = new PersonPostViewModel();
            return View("Create", person);
        }

        [HttpPost("create")]
        public async Task<IActionResult> Create(PersonPostViewModel person)
        {
            if (!ModelState.IsValid) return View("Create", person);
            
            if (await _unitOfWork.PersonRepository.FindByPersonEmailAsync(person.PersonEmail) is not null)
            {
                var error = new ErrorModel
                {
                    ErrorTitle = "Ett fel har inträffat när användaren skulle sparas!",
                    ErrorMessage = $"En person med Email {person.PersonEmail} finns redan i systemet"
                };
                return View("_Error", error);
            }



            var personToAdd = new Person
            {
                PersonUserName = person.PersonUserName,
                PersonTitle = person.PersonTitle,
                PersonName = person.PersonName,
                PersonLastName = person.PersonLastName,
                PersonEmail = person.PersonEmail,
                PersonPhone = person.PersonPhone,
                Password = person.Password
            };

            if (await _unitOfWork.PersonRepository.AddAsync(personToAdd))
            {
                if (await _unitOfWork.Complete())
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View("_Error", new ErrorModel { ErrorTitle = "Gick inte att spara användare", ErrorMessage = $"Ett fel inträffade när användare {person.PersonName} {person.PersonLastName} skulle sparas" });

        }



        [HttpGet("edit/{personId}")]
        public async Task<IActionResult> Edit(int personId)
        {
            var result = await _unitOfWork.PersonRepository.FindByIdAsync(personId);

        if (result is null)
            {
                return View("_Error", new ErrorModel { ErrorTitle = "Kunde inte hitta användare", ErrorMessage = $"Vi kunde inte hitta någon användare med id {personId}" });
            }

            var personToUpdate = new PersonUpdateViewModel
            {
                PersonId = result.PersonId,
                PersonUserName = result.PersonUserName,
                PersonTitle = result.PersonTitle,
                PersonName = result.PersonName,
                PersonLastName = result.PersonLastName,
                PersonEmail = result.PersonEmail,
                PersonPhone = result.PersonPhone,
            };

            return View("Edit", personToUpdate);
        }

        [HttpPost("edit/{personId}")]
        public async Task<IActionResult> Edit(int personId, PersonUpdateViewModel person)
        {
            try
            {
                if (!ModelState.IsValid) return View("Edit", person);

                var personToUpdate = await _unitOfWork.PersonRepository.FindByIdAsync(personId);

                if (personToUpdate is null)
                {
                    var notFoundError = new ErrorModel
                    {
                        ErrorTitle = "Användare saknas!",
                        ErrorMessage = $"Det gick inte att hitta användaren {person.PersonName} {person.PersonLastName}"
                    };

                    return View("_Error", notFoundError);
                }

                personToUpdate.PersonUserName  = person.PersonUserName;
                personToUpdate.PersonTitle  = person.PersonTitle;
                personToUpdate.PersonName  = person.PersonName;
                personToUpdate.PersonLastName  = person.PersonLastName;
                personToUpdate.PersonEmail  = person.PersonEmail;
                personToUpdate.PersonPhone  = person.PersonPhone;

                if (await _unitOfWork.PersonRepository.UpdateAsync(personToUpdate))
                {
                    if (await _unitOfWork.Complete())
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }

                return View("_Error", new ErrorModel {ErrorTitle = "Ett fel inträffade", ErrorMessage = "något gick fel när användaren skulle uppdateras"});
            }
            catch (Exception ex)
            {
                return View("_Error", new ErrorModel { ErrorTitle = "Ett fel inträffat", ErrorMessage = ex.Message});
            }
        }
        
        
        [Route("delete/{personId}")]
        public async Task<IActionResult> Delete(int personId)
        {
            try
            {
                var personToDelete = await _unitOfWork.PersonRepository.FindByIdAsync(personId);

                if (personToDelete is null) return RedirectToAction(nameof(Index));

                if (await _unitOfWork.PersonRepository.DeleteAsync(personToDelete))
                {
                    if(await _unitOfWork.Complete())
                    {
                        return RedirectToAction(nameof(Index));
                    }
                        
                }
                
                return View("_Error", new ErrorModel {ErrorTitle = "Ett fel inträffade när användaren skulle tas bort", ErrorMessage = $"Ett fel inträffade när användare id {personId} skulle raderas"});

            }

            
            catch (Exception ex)
            {
                return View("_Error", new ErrorModel {ErrorTitle = "Ett fel har inträffat", ErrorMessage = ex.Message});
                
            }
        }
    }
}

westcoast-education.web/Views/PersonsAdmin/Create.cshtml
@model westcoast_education.web.ViewModels.Persons.PersonPostViewModel

@{
    Layout = "_LayoutAdmin";
}

<section class="page">
    <h1 class="page-title">Lägg till användare</h1>
    <form class="shadow" asp-action="create" asp-controller="PersonsAdmin" method="post">
        <div class="form-control">
            <label asp-for="PersonUserName"></label>
            <input asp-for="PersonUserName" />
            <span class="error" asp-validation-for="PersonUserName"></span>
        </div>
        <div class="form-control">
            <label asp-for="PersonTitle"></label>
            <input asp-for="PersonTitle" />
            <span class="error" asp-validation-for="PersonTitle"></span>
        </div>
        <div class="form-control">
            <label asp-for="PersonName"></label>
            <input asp-for="PersonName" />
            <span class="error" asp-validation-for="PersonName"></span>
        </div>
        <div class="form-control">
            <label asp-for="PersonLastName"></label>
            <input asp-for="PersonLastName" />
            <span class="error" asp-validation-for="PersonLastName"></span>
        </div>
        <div class="form-control">
            <label asp-for="PersonEmail"></label>
            <input asp-for="PersonEmail" />
            <span class="error" asp-validation-for="PersonEmail"></span>
        </div>
        <div class="form-control">
            <label asp-for="PersonPhone"></label>
            <input asp-for="PersonPhone" />
            <span class="error" asp-validation-for="PersonPhone"></span>
        </div>
        <div class="form-control">
            <label asp-for="Password"></label>
            <input asp-for="Password" />
            <span class="error" asp-validation-for="Password"></span>
        </div>

        <div class="form-control">
            <div class="buttons-container">
                <button type="Submit" class="btn btn-primary"><i class="fa-sharp fa-solid fa-floppy-disk"></i>
                    Spara</button>
                <a asp-action="index" asp-controller="PersonsAdmin" class="btn btn-warning"><i
                        class="fa-solid fa-arrow-left"></i>Avbryt</a>
            </div>
        </div>
    </form>
</section>

westcoast-education.web/Views/PersonsAdmin/Edit.cshtml
@model westcoast_education.web.ViewModels.Persons.PersonUpdateViewModel

@{
    Layout = "_LayoutAdmin";
}

<section class="page">
    <h1 class="page-title">Lägg till person</h1>
    <form class="shadow" asp-action="edit" asp-controller="PersonsAdmin" asp-route-personId=@Model.PersonId
    method="post">
        <div class="form-control">
            <label asp-for="PersonUserName"></label>
            <input asp-for="PersonUserName" />
            <span class="error" asp-validation-for="PersonUserName"></span>
        </div>
        <div class="form-control">
            <label asp-for="PersonTitle"></label>
            <input asp-for="PersonTitle" />
            <span class="error" asp-validation-for="PersonTitle"></span>
        </div>
        <div class="form-control">
            <label asp-for="PersonName"></label>
            <input asp-for="PersonName" />
            <span class="error" asp-validation-for="PersonName"></span>
        </div>
        <div class="form-control">
            <label asp-for="PersonLastName"></label>
            <input asp-for="PersonLastName" />
            <span class="error" asp-validation-for="PersonLastName"></span>
        </div>
         <div class="form-control">
            <label asp-for="PersonEmail"></label>
            <input asp-for="PersonEmail" />
            <span class="error" asp-validation-for="PersonEmail"></span>
        </div>
        <div class="form-control">
            <label asp-for="PersonPhone"></label>
            <input asp-for="PersonPhone" />
            <span class="error" asp-validation-for="PersonPhone"></span>
        </div>
        <div class="form-control">
            <label asp-for="Password"></label>
            <input disabled asp-for="Password" />
            <span class="error" asp-validation-for="Password"></span>
        </div>

        <div class="form-control">
            <div class="buttons-container">
                <button type="Submit" class="btn btn-primary"><i class="fa-sharp fa-solid fa-floppy-disk"></i>
                    Spara</button>
                <a asp-action="index" asp-controller="PersonsAdmin" class="btn btn-warning"><i
                        class="fa-solid fa-arrow-left"></i>Avbryt</a>
            </div>
        </div>
    </form>
</section>

westcoast-education.web/Views/PersonsAdmin/index.cshtml
@model IList<westcoast_education.web.ViewModels.Persons.PersonsListViewModel>

@{
    Layout = "_LayoutAdmin";
}

<section class="page">
    <h1>Lärare och Studenter</h1>
    <div class="table-container">
        <div>
            <a class="btn btn-primary" asp-action="create" asp-controller="PersonsAdmin">Lägg till användare</a>
        </div>
        <table>
            <thead>
                <tr>
                    <th></th>
                    <th>Användarnamn</th>
                    <th>Titel</th>
                    <th>Förnamn</th>
                    <th>Efternamn</th>
                    <th>Email</th>
                    <th>Telefon</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var person in Model)
                {
                    <tr>
                        <td class="edit-icon">
                            <a asp-action="Edit" asp-controller="PersonsAdmin" asp-route-personId=@person.PersonId><i
                                class="fa-solid fa-pen"></i></a>
                        </td>
                        <td>@person.PersonUserName</td>
                        <td>@person.PersonTitle</td>
                        <td>@person.PersonName</td>
                        <td>@person.PersonLastName</td>
                        <td>@person.PersonEmail</td>
                        <td>@person.PersonPhone</td>
                        <td><a class="delete-icon" asp-action="Delete" asp-controller="PersonsAdmin"
                            asp-route-personId=@person.PersonId><i class="fa-solid fa-trash-can"></i></a></td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
            </tfoot>
        </table>
    </div>
</section>