westcoast-education.web/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;

namespace westcoast_education.web.Controllers
{
    [Route("admin")]
    public class AdminController : Controller
    {
        

        public IActionResult Index()
        {
            return View("Index");
        }

        
    }
}

westcoast-education.web/Controllers/CoursesAdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using westcoast_education.web.Data;
using westcoast_education.web.Interfaces;
using westcoast_education.web.Models;
using westcoast_education.web.ViewModels;

namespace westcoast_education.web.Controllers


{
    [Route("coursesadmin")]
    public class CoursesAdminController : Controller
    {
        
        
        private readonly IUnitOfWork _unitOfWork;

        public CoursesAdminController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                
                var courses = await _unitOfWork.CourseRepository.ListAllAsync();
                

                var model = courses.Select(v => new CourseListViewModel
                {
                    CourseId = v.CourseId,
                    CourseNumber = v.CourseNumber,
                    CourseName = v.CourseName,
                    CourseTitle = v.CourseTitle,
                    CourseStartDate = v.CourseStartDate,
                    CourseEndDate = v.CourseEndDate

                }).ToList();
                
                return View("Index", model);
            }
            catch (Exception ex)
            {
                
                var error = new ErrorModel{
                    ErrorTitle = "Ett fel har inträffat när vi skulle hämta alla bilar",
                    ErrorMessage = ex.Message
                };

                return View("_Error", error);
            }
            
            
        }

        [HttpGet("create")]
        public IActionResult Create()
        {
            var course = new CoursePostViewModel();
            return View("Create", course);
        }

        [HttpPost("create")]
        public async Task<IActionResult> Create(CoursePostViewModel course)
        {
            try
            {
                if(!ModelState.IsValid) return View("Create", course);
                
            var exists = await _unitOfWork.CourseRepository.FindByCourseNumberAsync(course.CourseNumber);
            if (exists is not null)
            {
                var error = new ErrorModel
                {
                    ErrorTitle ="Ett fel har inträffat när kursen skulle sparas!",
                    ErrorMessage = $"En kurs med kursnummer {course.CourseNumber} finns redan i systemet"
                };

                return View("_Error", error);
            }

            var courseToAdd = new Course
            {
                CourseNumber = course.CourseNumber,
                CourseName = course.CourseName,
                CourseTitle = course.CourseTitle,
                CourseStartDate = course.CourseStartDate,
                CourseEndDate = course.CourseEndDate
            };

            

            if(await _unitOfWork.CourseRepository.AddAsync(courseToAdd))
            {
                if(await _unitOfWork.Complete())
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            var saveError = new ErrorModel
                {
                    ErrorTitle ="Ett fel har inträffat när kursen skulle sparas!",
                    ErrorMessage = $"Det inträffade ett fel när kursen med kursnummer {course.CourseNumber} skulle sparas"
                };

                return View("_Error", saveError);
            
            
            }
            catch (Exception ex)
            {
                
                var error = new ErrorModel
                {
                    ErrorTitle = "Ett fel har inträffat när vi skulle spara kursen",
                    ErrorMessage = ex.Message
                };

                return View("_Error", error);
            }
            

            
        }
         
         
          [HttpGet("edit/{courseId}")]
        public async Task<IActionResult> Edit(int courseId)
        {
            try
            {
                
                var result = await _unitOfWork.CourseRepository.FindByIdAsync(courseId);
                
                if (result is null){
                    var error = new ErrorModel
                    {
                        ErrorTitle = "Ett fel har inträffat när vi skulle hämta en kurs för redegering",
                        ErrorMessage = $"Vi hittar ingen kurs med id {courseId}"
                    };

                    return View("_Error", error);
               
                } 

                var model = new CourseUpdateViewModel
                {
                    CourseId = result.CourseId,
                    CourseNumber = result.CourseNumber,
                    CourseName = result.CourseName,
                    CourseTitle = result.CourseTitle,
                    CourseStartDate = result.CourseStartDate,
                    CourseEndDate = result.CourseEndDate

                };
                return View("Edit", model);

            }
            catch (Exception ex)
            {
                
                var error = new ErrorModel{
                    ErrorTitle = "Ett fel har inträffat när vi hämtar kurs för redegering",
                    ErrorMessage = ex.Message
                };

                return View("_Error", error); 
            }
            
            
            
        }

        [HttpPost("edit/{courseId}")]
        public async Task<IActionResult> Edit(int courseId, CourseUpdateViewModel course)
        {
            try
            {
                if(!ModelState.IsValid) return View("Edit", course);

                // var courseToUpdate = _context.Courses.SingleOrDefault(c => c.CourseId == courseId);
                var courseToUpdate = await _unitOfWork.CourseRepository.FindByIdAsync(courseId);
                if(courseToUpdate is null) return RedirectToAction(nameof(Index));

                courseToUpdate.CourseNumber = course.CourseNumber;
                courseToUpdate.CourseName = course.CourseName;
                courseToUpdate.CourseTitle = course.CourseTitle;
                courseToUpdate.CourseStartDate = course.CourseStartDate;

                if(await _unitOfWork.CourseRepository.UpdateAsync(courseToUpdate)){
                    if(await _unitOfWork.Complete()){
                        return RedirectToAction(nameof(Index));
                    }
                }
                
                 var error = new ErrorModel
                {
                    ErrorTitle = "Ett fel har inträffat när vi skulle spara kursen",
                    ErrorMessage = $"Ett fel inträffade när vi skulle uppdatera bilen med kursnummer{courseToUpdate.CourseNumber}"
                };

                return View("_Error", error);
            }
            catch (Exception ex)
            {
                
                var error = new ErrorModel
                {
                    ErrorTitle = "Ett fel har inträffat när vi skulle spara kursen",
                    ErrorMessage = ex.Message
                };

                return View("_Error", error);
            }
            
        }

        [Route("delete/{courseId}")]
        public async Task<IActionResult> Delete(int courseId)
        {
            try
            {
                
                var courseToDelete = await _unitOfWork.CourseRepository.FindByIdAsync(courseId);

                if(courseToDelete is null) return RedirectToAction(nameof(Index));

                
                if(await _unitOfWork.CourseRepository.DeleteAsync(courseToDelete))
                {
                    if(await _unitOfWork.Complete())
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                var error = new ErrorModel{
                    ErrorTitle = "Ett fel har inträffat när kursen skulle raderas",
                    ErrorMessage = $"Ett fel inträffade när kursen med kursnummer {courseToDelete.CourseNumber} skulle raderas"
                };

                return View("_Error", error);
                
            }
            catch (Exception ex)
            {
                
               var error = new ErrorModel{
                    ErrorTitle = "Ett fel har inträffat när kursen skulle raderas",
                    ErrorMessage = ex.Message
                };

                return View("_Error", error);
            }
            
        }

        
    }
}

westcoast-education.web/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using westcoast_education.web.Data;

namespace westcoast_education.web.Controllers
{
    [Route("courses")]
    public class CoursesController : Controller
    {
        private readonly WestcoastEducationContext _context;
        public CoursesController(WestcoastEducationContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var courses =  await _context.Courses.ToListAsync();
            return View("index", courses);
        }

       
    }
}

westcoast-education.web/Controllers/PersonsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using westcoast_education.web.Data;

namespace westcoast_education.web.Controllers
{
    [Route("persons")]
    public class PersonsController : Controller
    {
      
        private readonly WestcoastEducationContext _context;
        public PersonsController(WestcoastEducationContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var persons =  await _context.Persons.ToListAsync();
            return View("index", persons);
        }

       
    }
}

westcoast-education.web/Views/Shared/_Error.cshtml
@model westcoast_education.web.Models.ErrorModel

@{
    Layout = "_LayoutAdmin";
}

<section class="page">
    <p class="error-icon"><i class="fa-regular fa-biohazard"></i></p>
    <h1 class="error-page-title">@Model.ErrorTitle</h1>
    <p class="text-secondary">@Model.ErrorMessage</p>
</section>

westcoast-education.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script src="https://kit.fontawesome.com/9e7bc46c24.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/6af4ecbb39.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/41bdce1ad7.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/4907559fcc.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="stylesheet" href="~/css/navigation.css">
    <link rel="stylesheet" href="~/css/colors.css">
    <link rel="stylesheet" href="~/css/utilities.css">
    <link rel="stylesheet" href="~/css/landing-page.css">
    @RenderSection("styles", false)
    <title>@ViewBag.PageTitle - Westcoast Education</title>
</head>
<body>
    <header>
        <nav class="navbar">
            <h1 class="logo"><span class="text-primary"><i class="fa-solid fa-school"></i>Westcoast </span>Education</h1>
            <ul>
                <a asp-action="index" asp-controller="Home">Start</a>
                <a asp-action="index" asp-controller="Courses">Kurser</a>
                <a asp-action="index" asp-controller="Persons">Användare</a>
                <a asp-action="index" asp-controller="Admin"><i class="fa-solid fa-gear"></i></a>
                
            </ul>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>
</body>
</html>

westcoast-education.web/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/9e7bc46c24.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/6af4ecbb39.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/41bdce1ad7.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/4907559fcc.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/css/styles.css">
    <link rel="stylesheet" href="~/css/colors-admin.css">
    <link rel="stylesheet" href="~/css/navigation-admin.css">
    <link rel="stylesheet" href="~/css/tables.css">
    <link rel="stylesheet" href="~/css/utilities.css">
    <title>Westcoast Education</title>
</head>

<body>
    <header>
        <nav class="navbar">
            <h1 class="logo"><a asp-action="Index" asp-controller="Home"><span
                        class="navbar-logo-primary-text>Westcoast"><i class="fa-solid fa-school"></i>Westcoast</span>
                    Education</a></h1>
            <ul>
                <li><a asp-action="Index" asp-controller="Admin">Start</a></li>
                <li><a asp-action="Index" asp-controller="CoursesAdmin">Alla kurser</a></li>
                <li><a asp-action="Index" asp-controller="PersonsAdmin">Användare</a></li>
            </ul>
        </nav>
    </header>
    <main>
        @RenderBody()
    </main>
</body>
</html>